#!/bin/bash

###########################################################################
## POSTINSTALL CONFIGURATION                                             ##
##  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  ##
##

pAPP="libapache2-mod-adex"
vAPP="1.1.2405"
dAPP="/usr/share/apache2/adex"

dMA="/etc/apache2/mods-available"
dME="/etc/apache2/mods-enabled"

mOFF=("autoindex")
mON=("autoindex-adex" "alias" "include")

##
##                                                                       ##
##  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  #  ##
###########################################################################



echo "[`date +"%Y-%m-%d %H:%M:%S"`] Starting postinstall script..."
echo "                      package: $pAPP"
echo "                      version: $vAPP"
fLog="/tmp/postinst-${pAPP}.log"
echo "$pAPP $vAPP" > $fLog
cd $dAPP


read -p "Apache2 modules directory location: [${dMA}] " sMA
read -p "Apache2 emabled modules location: [${dME}] " sME
if [ "$sMA" != "" ]; then dMA="${sMA}"; fi
if [ "$sME" != "" ]; then dME="${sME}"; fi


echo -n "[`date +"%Y-%m-%d %H:%M:%S"`] Creating symlinks and shortcuts..."
echo ">>> ln -s $dAPP/module.conf ${dMA}/autoindex-adex.conf" >> $fLog
ln -s $dAPP/module.conf ${dMA}/autoindex-adex.conf >> $fLog 2>&1
echo -n "."
echo ">>> ln -s $dMA/autoindex.load ${dMA}/autoindex-adex.load" >> $fLog
cd $dMA
ln -s ./autoindex.load ./autoindex-adex.load >> $fLog 2>&1
echo -n "."
echo " ok."


echo -n "[`date +"%Y-%m-%d %H:%M:%S"`] Configuring required apache2 modules..."
cd $dME
len=${#mOFF[*]}
i=0
while [ $i -lt $len ]; do
	if [ "`command -v a2dismod`" != "" ]; then
		echo ">>> a2dismod ${mOFF[$i]}" >> $fLog
		a2dismod ${mOFF[$i]} >> $fLog 2>&1
	else
		echo ">>> rm -f ${dME}/${mOFF[$i]}.*" >> $fLog
		rm -f ./${mOFF[$i]}.* >> $fLog 2>&1
	fi
	echo -n "."
	let i++
done
len=${#mON[*]}
i=0
while [ $i -lt $len ]; do
	if [ "`command -v a2enmod`" != "" ]; then
		echo ">>> a2enmod ${mON[$i]}" >> $fLog
		a2enmod ${mON[$i]} >> $fLog 2>&1
	else
		echo ">>> ln -s ${dMA}/${mON[$i]}.* ${dME}/" >> $fLog
		ln -s ${dMA}/${mON[$i]}.* ./ >> $fLog 2>&1
	fi
	echo -n "."
	let i++
done
echo " ok."


echo -n "[`date +"%Y-%m-%d %H:%M:%S"`] Reloading server configuration..."
if [ "`command -v systemctl`" != "" ]; then
	echo ">>> systemctl reload apache2" >> $fLog
	systemctl reload apache2 >> $fLog 2>&1
else
	echo ">>> /etc/init.d/apache2 reload" >> $fLog
	/etc/init.d/apache2 reload >> $fLog 2>&1
fi
echo -n "."
echo " ok."


cd $dAPP
echo "[`date +"%Y-%m-%d %H:%M:%S"`] Postinstall log saved: $fLog"
echo "[`date +"%Y-%m-%d %H:%M:%S"`] Done."
