var APP={};
var fType={};

var thisdir=window.location.origin+window.location.pathname;



//////////////////////////////////////////////////
// document initialization                      //
//////////////////////////////////////////////////

$(document).ready(function()
{
	getEnvVars();
	setFileTypes();
	makeTitle();
	formatTable();
	createObjects();
	bindEvents();
});



//////////////////////////////////////////////////
// setting global variables                     //
//////////////////////////////////////////////////

// // // // // // // // // // // // // // // // //
// from apache2 EnvVars
function getEnvVars()
{
	$('#VARS span').each(function(){ APP[$(this).attr('title')]=$(this).html(); });
	$('#VARS').remove();
}

// // // // // // // // // // // // // // // // //
// file extensions grouped by file types
function setFileTypes()
{
	fType['image']=['ico','gif','jpg','jpeg','jpc','jp2','jpx','xbm','wbmp','png','bmp','tif','tiff','psd','svg','webp','avif'];
	fType['video']=['avi','webm','wmv','mp4','m4v','ogm','ogv','mov','mkv','mpg','mpeg','flv','3gp','asf'];
	fType['audio']=['wav','mp3','mp2','ogg','oga','m4a','flac','aac','wma','mka','ac3'];
	fType['text']=['txt','css','ini','conf','log','htaccess','passwd','ftpquota','sql','js','ts','jsx','tsx','mjs','json','sh','config','php','php4','php5','phps','phtml','htm','html','shtml','xhtml','xml','xsl','m3u','m3u8','pls','cue','bash','vue','eml','msg','csv','bat','twig','tpl','md','gitignore','less','sass','scss','c','cpp','cs','py','go','zsh','swift','map','lock','dtd','svg','asp','aspx','asx','asmx','ashx','jsp','jspx','cgi','dockerfile','ruby','yml','yaml','toml','vhost','scpt','applescript','csx','cshtml','coffee','cfm','rb','graphql','mustache','jinja','http','handlebars','java','es','es6','markdown','wiki','tmp','top','bot','dat','bak','htpasswd','pl'];
	fType['document']=['doc','docx','xls','xlsx','pdf','ppt','pptx','ai','psd','dxf','xps','rar','odt','ods'];
}



//////////////////////////////////////////////////
// transforming layout                          //
//////////////////////////////////////////////////

// // // // // // // // // // // // // // // // //
// sets document title and header
function makeTitle()
{
	var pName=decodeURIComponent(APP['REQUEST_URI']);
	pName=pName.replace('?'+APP['QUERY_STRING'], '');
	
	if (pName=='' || pName=='/') $('title').html(APP['HTTP_HOST']+' - '+APP['ShortName']);
	else $('title').html(APP['HTTP_HOST']+' ['+pName+'] - '+APP['ShortName']);
	
	var title='<a href="/" class="host">'+APP['HTTP_HOST']+'</a>';
	if (pName!='' && pName!='/')
	{
		var i=1;
		var pArr=pName.split('/');
		var pUrl='';
		for (i=1;i<pArr.length;i++)
		{
			pUrl+='/'+encodeURIComponent(pArr[i]);
			if (i==pArr.length-2) pArr[i]='<strong>'+pArr[i]+'</strong>';
			title+=' / <a href="'+pUrl+'/">'+pArr[i]+'</a>';
		}
	}
	$('header h1').html(title);
}


// // // // // // // // // // // // // // // // //
// parses original table generated by autoindex and creates fancy one instead that
function formatTable()
{
	var cols=['icon fhref', 'filename fhref', 'modtime', 'size', 'description', 'actions'];
	var thead=[];
	var tbody=[];
	
	var indexfile='';
	
	$('table tr').each(function(i)
	{
		if (i==0) $(this).children('th').each(function(y){ thead.push($(this).html()); });
		if (i>1)
		{
			var trow=[];
			$(this).children('td').each(function(y){ trow.push($(this).html()); });
			if (trow.length>1) trow.push('&nbsp;');
			tbody.push(trow);
		}
	});
	thead.push('&nbsp;');
	
	$('table').html('');
	$('table').remove();
	
	$('main').append('<table><thead><tr></tr></thead><tbody></tbody></table>');
	for (th in thead) $('table thead tr').append('<th class="'+cols[th]+'">'+thead[th]+'</th>');
	for (tb in tbody)
	{
		var trow='';
		for (td in tbody[tb]) trow+='<td class="'+cols[td]+'">'+tbody[tb][td]+'</td>';
		if (trow!='') $('table tbody').append('<tr class="item'+tb+'">'+trow+'</tr>');
	}
	
	$('table tr th.modtime a').html('Modified');
	$('table tr .description').hide();
	$('table tr .actions').hide();
	
	$('table tbody tr').each(function(i)
	{
		$(this).children('td.icon').append('<span class="hidden">'+getPrettyName($(this).children('td.filename').children('a').html()+'</span>'));
		
		if ($(this).children('td.filename').children('a').html()=='Parent Directory')
		{
			$(this).children('td.filename').children('a').html('<strong>.&nbsp;&nbsp;.&nbsp;&nbsp;&#10548;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong>');
			$(this).addClass('levelup');
		}
		
		if ($(this).children('td.filename').children('a').html()=='!index')
		{
			$(this).hide();
			indexfile=$(this).children('td.filename').children('a').attr('href');
		}
		
		var desc=$(this).children('td.description').html();
		if (desc!='' && desc!='&nbsp;' && desc!=undefined) $(this).children('td.filename').append('<br /><small>'+desc+'</small>');
		
		$(this).children('td.fhref').children('a').attr('rel', i);
	});
	
	if (indexfile!='') parseIndexFile(indexfile);
}


// // // // // // // // // // // // // // // // //
// do some stuff with another items on page
function createObjects()
{
	$('body').children('address').remove();
}


// // // // // // // // // // // // // // // // //
// parse and use data from !index file
function parseIndexFile(iurl)
{
	$.ajax(
	{
		type: 'GET',
		url: iurl,
		success: function(result)
		{
			result=result.replace(/	/gi, '');
			result=result.replace(/\r/gi, "\n");
			result=result.replace(/\n\n/gi, "\n");
			var lines=result.split("\n");
			for (l in lines)
			{
				var line=lines[l].split(':');
				if (line.length>1 && line[0]!='')
				{
					var itemid=findItemId(line[0]);
					if (itemid>-1)
					{
						var opts=line[1].split(';');
						for (o in opts)
						{
							var opt=opts[o].split('=');
							if (opt[0]=='icon') $('main table tbody tr.item'+itemid+' td.icon img').attr('src', opt[1]);
							if (opt[0]=='name') $('main table tbody tr.item'+itemid+' td.icon span').html(opt[1]);
							if (opt[0]=='description')
							{
								if ($('main table tbody tr.item'+itemid+' td.filename small').html()==undefined) $('main table tbody tr.item'+itemid+' td.filename').append('<br /><small></small>');
								$('main table tbody tr.item'+itemid+' td.filename small').html(opt[1]);
								$('main table tbody tr.item'+itemid+' td.description').html(opt[1]);
							}
						}
					}
				}
			}
		}
	});
}



//////////////////////////////////////////////////
// binding actions to events                    //
//////////////////////////////////////////////////

var navStarted=false;

function bindEvents()
{
	// // // // // // // // // // // // // // // // //
	// on window resize
	$(window).resize(function()
	{
		var bodyPT=$('header').height();
		bodyPT+=$('header').css('padding-top').replace('px', '')*1;
		bodyPT+=$('header').css('padding-bottom').replace('px', '')*1;
		$('body').css('padding-top', bodyPT+'px');
		
		var mainH=$(window).height();
		mainH=mainH-$('footer').height();
		mainH=mainH-($('main table').css('margin-top').replace('px', '')*2);
		mainH=mainH-bodyPT;
		$('aside.fitem').css('height', mainH+'px');
		
		if (!$('aside.fitem').hasClass('hidden'))
		{
			var prevH=$('aside.fitem').height()-$('aside.fitem .info').height();
			$('aside.fitem .preview').css('height', prevH+'px');
		}
		
		$(window).scroll();
	});
	
	// // // // // // // // // // // // // // // // //
	// on vertical scroll
	$(window).scroll(function()
	{
		var pos=$(document).scrollTop();
		$('aside.fitem').css('margin-top', (pos+$('table').css('margin-top').replace('px','')*1)+'px');
	});
	
	
	// // // // // // // // // // // // // // // // //
	// on table row click
	$('table tbody tr td.fhref, table tbody tr td.fhref a').click(function()
	{
		var item={'id':-1, 'filename':''};
		
		var thisobj=$(this);
		if ($(this).hasClass('fhref')) thisobj=$(this).children('a');
		
		item['id']=thisobj.attr('rel');
		item['filename']=thisobj.attr('href');
		if (thisobj.parent('td').parent('tr').hasClass('levelup')) item['filename']='../';
		
		setTimeout(function()
		{
			if (navStarted!=true && item['id']>-1)
			{
				if (item['filename']!='../') window.location.hash='#'+item['filename'];
				else window.location.hash='';
			}
		}, 500);
		return false;
	});
	
	// // // // // // // // // // // // // // // // //
	// on table row doubleclick
	$('table tbody tr td.fhref, table tbody tr td.fhref a').dblclick(function()
	{
		navStarted=true;
		var thisobj=$(this);
		if ($(this).hasClass('fhref')) thisobj=$(this).children('a');
		window.location=thisobj.attr('href');
	});
	
	
	// // // // // // // // // // // // // // // // //
	// on url hash change
	$(window).bind("hashchange", function()
	{
		var hash=window.location.hash.replace('#', '');
		if (hash=='') closeFileBox();
		else
		{
			var itemid=findItemId(hash);
			if (itemid>-1) openFileBox(getFileItem(itemid));
		}
		return false;
	});
	
	
	// // // // // // // // // // // // // // // // //
	// on document ready
	
	$(window).resize();
	
	if (window.location.hash!='' && window.location.hash!='#')
	{
		var itemid=findItemId(window.location.hash.replace('#', ''));
		if (itemid>-1) openFileBox(getFileItem(itemid));
	}
}



//////////////////////////////////////////////////
// getting / setting file properties            //
//////////////////////////////////////////////////

// // // // // // // // // // // // // // // // //
// gets all details from table row to array
function getFileItem(item)
{
	var fitem={'id':item, 'type':'unknown', 'icon':'', 'name':'', 'filename':'', 'path':'', 'url':'', 'modtime':'', 'size':'-', 'description':''};
	$('table tbody tr.item'+item+' td').each(function()
	{
		if ($(this).hasClass('icon'))
		{
			fitem['icon']=$(this).children('a').children('img').attr('src');
			fitem['name']=$(this).children('span').html();
		}
		if ($(this).hasClass('filename'))
		{
			if (!$(this).parent('tr').hasClass('levelup')) fitem['filename']=$(this).children('a').html();
			else fitem['filename']='../';
			
			fitem['path']=thisdir+fitem['filename'];
			fitem['url']=thisdir+'#'+fitem['filename'];
			
			if (!$(this).parent('tr').hasClass('levelup'))
			{
				if (fitem['filename'].at(-1)=='/') fitem['type']='dir';
				else
				{
					var farr=fitem['filename'].split('.');
					fitem['type']=findFileType(farr[farr.length-1]);
				}
			}
			else fitem['type']='up';
		}
		if ($(this).hasClass('modtime')) fitem['modtime']=$(this).html();
		if ($(this).hasClass('size')) fitem['size']=$(this).html();
		if ($(this).hasClass('description')) fitem['description']=$(this).html();
	});
	return(fitem);
}


// // // // // // // // // // // // // // // // //
// returns file type by file extension
function findFileType(fextension)
{
	var ret='unknown';
	fextension=fextension.toLowerCase();
	for (key in fType)
	{
		for (ext in fType[key])
		{
			if (fextension==fType[key][ext]) ret=key;
		}
	}
	return(ret);
}

// // // // // // // // // // // // // // // // //
// returns file id from file name
function findItemId(filename)
{
	var ret=-1;
	$('table tbody a').each(function()
	{
		if ($(this).parent('td').hasClass('filename'))
		{
			if ($(this).attr('href')==filename) ret=$(this).attr('rel');
		}
	});
	return(ret);
}


// // // // // // // // // // // // // // // // //
// returns "pretty" human-readable file name
function getPrettyName(filename)
{
	var ret=filename;
	ret=ret.replace(/_/gi, ' ');
	ret=ret.replace(/-/gi, ' ');
	ret=ret.replace(/   /gi, ' - ');
	return(ret);
}



//////////////////////////////////////////////////
// file details and preview pane                //
//////////////////////////////////////////////////

// // // // // // // // // // // // // // // // //
// shows the file pane
function openFileBox(item)
{
	$('aside.fitem *').off('click');
	$('aside.fitem').html($('template.fitem').html());
	
	if ($('aside.fitem').hasClass('hidden'))
	{
		$('aside.fitem').removeClass('hidden');
		$('table').addClass('side');
	}
	
	
	$('aside.fitem img').attr('src', item['icon'].replace('.32.png', '.64.png'));
	$('aside.fitem h1').html(item['name']);
	
	$('aside.fitem p.description').html('');
	if (item['description']!='' && item['description']!='&nbsp;') $('aside.fitem p.description').html(item['description']+'<br />');
	$('aside.fitem p.description').append('<em>'+item['path']+'</em>');
	
	$('aside.fitem .actions').html('');
	$('aside.fitem .actions').append('<a class="open" href="'+item['path']+'" target="_blank">Open / Download</a>');
	$('aside.fitem .actions').append('<a class="cpurl" href="#">Copy URL</a>');
	$('aside.fitem .actions').append('<a class="share" href="#">Share</a>');
	$('aside.fitem .actions').append('<a class="close fr" href="#">Close</a>');
	
	
	//$('aside.fitem h1').click(function(){ navigator.clipboard.writeText(item['path']); });
	$('aside.fitem .actions a').click(function()
	{
		if ($(this).hasClass('close')) window.location.hash='';
		if ($(this).hasClass('cpurl'))
		{
			try
			{
				navigator.clipboard.writeText(item['path']);
				alert('Copied to clipboard.');
			}
			catch(e){ prompt('Clipboard is blocked, copy URL from here:', item['path']); }
		}
		if ($(this).hasClass('share')) window.open('https://www.addtoany.com/share#title='+item['name']+'&url='+item['path'], 'add2any', 'width=800,height=600,location=no,menubar=no,status=no,titlebar=no,toolbar=no');
		if (!$(this).hasClass('open')) return false;
	});
	
	
	if (item['type']=='image') $('aside.fitem .preview').html('<img src="'+item['path']+'" alt="" />');
	if (item['type']=='audio') $('aside.fitem .preview').html('<audio controls src="'+item['path']+'"></audio>');
	if (item['type']=='video') $('aside.fitem .preview').html('<video controls src="'+item['path']+'"></video>');
	if (item['type']=='text')
	{
		$('aside.fitem .preview').remove();
		$('aside.fitem').append('<iframe class="preview" src="'+item['path']+'"></iframe>');
	}
	if (item['type']=='document')
	{
		$('aside.fitem .preview').remove();
		$('aside.fitem').append('<iframe class="preview" src="https://docs.google.com/viewer?embedded=true&amp;hl=en&amp;url='+item['path']+'"></iframe>');
	}
	if (item['type']=='unknown') $('aside.fitem .preview').html('(no preview available)');
	
	$(window).resize();
}

// // // // // // // // // // // // // // // // //
// closes the file pane
function closeFileBox()
{
	$('aside.fitem').addClass('hidden');
	$('table').removeClass('side');
	$('aside.fitem *').remove();
}
